name: CI/CD Master Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  filter-paths:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters:
            backend:
              - "backend/**"
            frontend:
              - "frontend/**"
            terraform:
              - "terraform/**"
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm install
      - name: Run CSpell
        run: npm run cspell
      - name: Run Linter
        run: npm run lint
  # test-backend:
  #   needs: filter-paths
  #   if: needs.filter-paths.outputs.backend == 'true'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4
  #     - name: Setup Node
  #       uses: actions/setup-node@v4
  #     - name: Install Backend Dependencies
  #       run: cd ./backend && npm install
  #     - name: Build Backend
  #       run: cd ./backend && npm run build
  #     - name: Test Backend
  #       run: cd ./backend && npm run test
  # push-backend-image:
  #   needs: test-backend
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4
  #     - name: Authenticate to Google Cloud
  #       uses: google-github-actions/auth@v2
  #       with:
  #         credentials_json: "${{ secrets.GCP_SA_KEY }}"
  #     - name: Set Up Docker
  #       uses: docker/setup-buildx-action@v3
  #     - name: Configure Docker
  #       run: gcloud auth configure-docker us-east1-docker.pkg.dev
  #     - name: Build & Push Backend Image
  #       run: cd ./backend && docker buildx build --platform linux/amd64 -t us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/app/backend:latest --push .
  # deploy-backend:
  #   needs: push-backend-image
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Authenticate to Google Cloud
  #       uses: google-github-actions/auth@v2
  #       with:
  #         credentials_json: "${{ secrets.GCP_SA_KEY }}"
  #     - name: Deploy to Cloud Run
  #       uses: google-github-actions/deploy-cloudrun@v2
  #       with:
  #         service: backend
  #         region: us-east1
  #         image: us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/app/backend:latest
  #         project_id: ${{ secrets.GCP_PROJECT_ID }}
  # test-frontend:
  #   needs: filter-paths
  #   if: needs.filter-paths.outputs.frontend == 'true'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4
  #     - name: Setup Node
  #       uses: actions/setup-node@v4
  #     - name: Install Frontend Dependencies
  #       run: cd ./frontend && npm install
  #     - name: Build Frontend
  #       run: cd ./frontend && npm run build
  #     - name: Test Frontend
  #       run: cd ./frontend && npm run test
  # push-frontend-image:
  #   needs: test-frontend
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4
  #     - name: Authenticate to Google Cloud
  #       uses: google-github-actions/auth@v2
  #       with:
  #         credentials_json: "${{ secrets.GCP_SA_KEY }}"
  #     - name: Set Up Docker
  #       uses: docker/setup-buildx-action@v3
  #     - name: Configure Docker
  #       run: gcloud auth configure-docker us-east1-docker.pkg.dev
  #     - name: Build & Push Frontend Image
  #       run: cd ./frontend && docker buildx build --platform linux/amd64 -t us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/app/frontend:latest --push .
  # deploy-frontend:
  #   needs: push-frontend-image
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Authenticate to Google Cloud
  #       uses: google-github-actions/auth@v2
  #       with:
  #         credentials_json: "${{ secrets.GCP_SA_KEY }}"
  #     - name: Deploy to Cloud Run
  #       uses: google-github-actions/deploy-cloudrun@v2
  #       with:
  #         service: frontend
  #         region: us-east1
  #         image: us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/app/frontend:latest
  #         project_id: ${{ secrets.GCP_PROJECT_ID }}
